### ISSUE TITLE
[$0 bounty] When clicking on the username to login and all text fields is now very slow

### ISSUE THREAD

**Issue by TaylorFrazier** [Emrals/Flutter#145]

**Comment by TaylorFrazier** [comment]
To replicate  this issue click on username and password back and forth a few times.

**Comment by britannio** [comment]
I cannot reproduce this. Nothing has really changed either to cause this. Maybe it's a Flutter 1.6 issue?

**Comment by TaylorFrazier** [comment]
Seems ok now
