### ISSUE TITLE
Style signup to look like previous app (use login styles)

### ISSUE THREAD

**Issue by fredfalcon** [Emrals/Flutter#16]
![screenshot_20190203-004051](https://user-images.githubusercontent.com/57934/52173301-d9b61800-274f-11e9-9a8d-c0908438c921.png)

**Comment by mikeumus** [comment]
This is what the Flutter login screen looks like currently:

<img width="404" alt="screen shot 2019-02-02 at 11 35 28 pm" src="https://user-images.githubusercontent.com/57934/52172719-77efb100-2743-11e9-8f21-9893a12daaee.png">

@TaylorFrazier, the only differences are the:
- width of the login button matching the input fields
- version number
- Forgot password link

I can add these three, should I just add a static "Forgot password" link for now?

**Comment by TaylorFrazier** [comment]
@mikeumus the signup is /signup this is /login - you'll see a difference - the forgot password is there with a recent push.

**Comment by mikeumus** [comment]
Oh I see. This ticket is for the /signup page and not the /login screen!

**Comment by mikeumus** [comment]
So this is what we have in the production Emrals app now:

![screenshot_20190203-004051](https://user-images.githubusercontent.com/57934/52173301-d9b61800-274f-11e9-9a8d-c0908438c921.png)

Just confirming this is what we want for the Flutter /signup page.

**Comment by TaylorFrazier** [comment]
This task is technically done - feel free to open another task for show password and any other related tasks
