### ISSUE TITLE
After deleting post the list should refresh to remove that

### ISSUE THREAD

**Issue by flutteradv** [Emrals/Flutter#181]

**Comment by TaylorFrazier** [comment]
Thanks, this works.  Can we also say the word “delete” on the button?

**Comment by flutteradv** [comment]
we can add but it covers a photo more

**Comment by TaylorFrazier** [comment]
Can make it a small button like this 
![083A849C-21C2-4D09-817B-A40470FF5B67](https://user-images.githubusercontent.com/41766869/65382925-aa065100-dcdb-11e9-9ba9-a15d398565e4.jpeg)

**Comment by flutteradv** [comment]
I'll do it
