### ISSUE TITLE
Paste text color is hard to see on send page

### ISSUE THREAD

**Issue by TaylorFrazier** [Emrals/Flutter#34]
![8bf3e1b8-7ae2-4a61-aaa2-2157d9080996](https://user-images.githubusercontent.com/41766869/52533405-8b7db780-2d01-11e9-86a3-31e080e9ac54.png)

**Comment by mevans** [comment]
![](https://lh3.googleusercontent.com/9oUn2vyIFHW-ars-6-vvQKj82N-e_piTDuq-cmmPETG8H5vqGDJQpUDUC7LGNpCrJaPjiBPko7KW_aca1UGm9DcoVpT-zPRdZu9C_4EMCZz5aDLw18w6q1qrtc49OY5VK9bOI7e59Tlli8-wjrOxHcANAFoYJCM6ipr8wpd02ylvCpTKODyh9PsoNiPptzOaohkmNOFmm-K6IZDWCNKzOivF-Q4AtpEhLkpW46_smsKhAsBRmCphxQ3xHzKpQWglaA4F-6wioZRPZOYKOKV8w3vBU_9vJS2NPhf1F_uqFOapH0KvfvZ19SE6fCoZgOnBSvf5MtXLF7nzLzvLTC3tseYcutyB2UoJaS92qDLYaArNPWZ2kNkync_1HD0AK5RmFaKwfOwxZhxxz3nyHzAhdD3_vWAOW4IVlZCZ6CMFUvoOSPNMPZIl2CWciWWH1g3DGcYMmTlrlwhL8UigNS4W7hJc2Ndt9r2zjvZR0sM7oKoSWCH14xFbJrt3FY8DFCdsaAlOJ0IJCA2ue7xoX3spZQ-lrMlDaNxsNJr9kJPGw7oPeYDEc_mrZRT49Ncjw-YZ6siG089y1InTzP77NyDWIlEPU236Qc9IOw7m7uJMkfK2GTwaaucqvfZOv54T-3FxYRuHemqDsQr7lN6uS6BOksZx5LYHqeg=w888-h1402-no)

This issue not seen on Stock Android 8.0

**Comment by TaylorFrazier** [comment]
yes, happening only on iOS

**Comment by TaylorFrazier** [comment]
This was fixed in a new version of Flutter
