### ISSUE TITLE
show reports on map

### ISSUE THREAD

**Issue by TaylorFrazier** [Emrals/Flutter#41]

**Comment by TaylorFrazier** [comment]
Reports are no longer showing on map - @britannio can you please take a look?

**Comment by britannio** [comment]
[Screenshot](https://lh3.googleusercontent.com/C0mTpbF0g4XLqqGlTXxRBvvxW3OdjUaUyQ3iaetoimJGe6vyf-uXBoPrAfM166Qug5pW8LoVX93DdizV_DswIArhHIIFDnzbrtPwfX-jHQHJdTUFY-PDkJD7tbNhyFCjBpoNbqk1zrABRj5_phTLpscVKhQln2Fe5LRxNMi8EGU1YDyC5eQQbqC1g1kNG7lADRaWuU8mcZytmQ5tBDz5EO7sgodhwhHPrVA33cTdbfTRehs5mkVDPAgbG2w-KuCsAPv9Wnzgzctdto8xBd6nabsEf1FwuzNf269jfHUjOMbTyVcshnUOej8fY4R-Po6M43HM3lCzImnVSSDbXdM2POwH8yzLH0oHsCrOgxdlYMGrMX3JdCUpXwe0NAXLOa0XsC4a4tvIpwmX-FXWF1_JHWBZc7smy-ATKC9Q_lvmUALAbLgx82U89vv0ZhQe-l2pxSQ5Ql7I9CvbYVYYAo3A_Yu6Zaq6gR6lviu0e8fERN0M_QcktqD6eoI-j6Litpk3D-oNyp3KF8rc7hjusxpoByZd66Tt5rZ6oDlGEf4YBwCArYPVb0ybBzUygEPiKSa7TNd1UBsafT5OJSfJ34shWOXlGA4BOi7-EVnM24gBvd9zkXvFeKgNBKUrKJH4UeFrnE692z4ozPUuHdQsmnFlNkg2Nt5X29K4uBNaqglyb21_o9deVWJXlqsNw_3tWDkn0KrO4JyfJoPiXnPpYBlJPyxBTA=w494-h878-no)
They're showing for me. Is the behaviour incorrect?

**Comment by TaylorFrazier** [comment]
![626E252E-CAD4-43CE-8122-F4E1EB95DBE8](https://user-images.githubusercontent.com/41766869/59825985-60d0ea80-9303-11e9-957b-364b771814d6.png)
I see a rapidly flickering screen on iOS

**Comment by britannio** [comment]
Not sure how to debug this. The google maps package is still in developers preview so if you can reproduce this locally then play around with it and if you can't fix it then it might be worth filing an issue on the flutter repo.

**Comment by TaylorFrazier** [comment]
It was working fine before.  Can we roll back?  Perhaps you can take a look on the iOS simulator?

**Comment by britannio** [comment]
Is this still an issue? The map no longer crashes for me.

**Comment by TaylorFrazier** [comment]
The most 50 or so recent reports are shown however it is no longer centering the map on the current location as it used to before https://github.com/Emrals/Flutter/commit/66040f8b4474eba7dba05f9917576933d5947598

**Comment by britannio** [comment]
Can you add an option to the API to specify the radius that reports are selected from? Then reports can be sequentially fetched in batches of 50 or so. This way allows relevant reports to be shown faster. Increasing the default zoom level will work well in conjunction with this change.

**Comment by britannio** [comment]
Centring to my location is working.

**Comment by TaylorFrazier** [comment]
It centers on load?  You can get the closest reports using the api.  See the closest api call.

**Comment by britannio** [comment]
Yeah, getting the location is asynchronous so it takes a second or two.
I know but how it isn't optimal for this use case. How would the app decide when to stop fetching the next batch of reports? If the user is zoomed in to a small location then the API only needs to return a small number of reports instead of 50.

**Comment by TaylorFrazier** [comment]
![8F9DAD28-8DE3-4523-9F83-B83554AC56C4](https://user-images.githubusercontent.com/41766869/61181466-f2770380-a5f4-11e9-99ae-0f9edb3d5359.png)

Waited a while, it’s not auto centering on my location when I tap the map icon.  For now the closest 50 is good until we have more reports.

**Comment by TaylorFrazier** [comment]
Will open new issues
